#!/bin/sh
#inkVerbSerf!

# This is a sample serf
## These are additional notes
## These are more additional notes

# How to use:
## ./serf [ setting 1 ] [ setting 2 ] [ setting 3 - optional ]

# Eg:
## ./serf set1 set2
## ./serf set1 set2 opt3

hierarchy=primary			# Choose: primary (works by itself, may use secondaries or tertiaries); secondary (can work by itself, but not normally, may use other secondaries or tertiaries); tertiary (cannot run by itself, must be run by a secondary or primary);oversight (uses primaries)
vsetnames=( "Set 1" "Set two" etc )	# "Pretty" names for each Setting, capitalize first word only, must be in order of Settings
voptnames=( "Food" "Your name" etc )	# "Pretty" names for each Option, capitalize first word only, must be in order of Options
vsetslugs=( ip6add on_off count )	# Unique "machine_name" for each Setting, must be unique and in order of Settings
voptslugs=( breakfast name color dom )	# Unique "machine_name" for each Option, must be unique and in order of Options
vsettypes=( IP6 Choice Int )		# Value types for settings in # Validity check functions, must be in order of settings, Choice settings must be one lowercase letter for the key and all others normal numbers in array order
vopttypes=( Choice az HEX Domain )	# Value types for options in # Validity check functions, must be in order of Options
voptflags=( b l u d )			# "Flags" to be used to proceed optional settings, must be in order of Options
usedby=( serfalso serf worker )		# List other serfs that make use of this serf, no particular order
useserfs=( anotherserf anotherserfwik )	# List other serfs used in this serf, please preserve order of appearance
useconfigs=( sitenameip siteurilist )	# List config files of any kind used in this serf, please preserve order of appearance
usagenotes="This serf is a test serfs. It is useful in developing yeo."
					# OPTIONAL VARIABLES, only required for Options with multiple choice
voptFC_X="one two three"	#OPTNL	# Set the space-separated list of multiple choices for the Flag -X
voptFC_b="eggs spam waffles"	#OPTNL	# eg: This is an space-separated list of choices for the Option -b Flag
vsetMC_1="hay straw wheat"	#OPTNL	# eg: This is an space-separated list of choices for the Setting with the [1] key
					#
					# Skip two lines after meta
SETTING1=$1				# Set inline variables first
SETTING2=$2

echo "The rest goes here."		# This is where the rest of the working script begins
					# Leave one blank line at the end for easier editing
