#!/bin/bash
#inkVerbYeo! verb.ink

# This is the "Yeoman" who manages a Verber by interacting with "Serfs", "Knights", the "Donjon", et cetera.
## This uses "yeo" to execute commands relevant to a Verber, similarly to how "apt", "yum", and "pacman" manage packages.
## yeo streamlines help queries, checks for required parameters, and provides a production-worthy layer of "fool-proofing".
## yeo retrieves available options, tools, settings, notes, parameter requirements, et cetera from the Verber assets themselves using functions & tools like grep and occasionally a central index. This is partially why formatting Serfs is important.
## This is NOT at all affiliated with http://yeoman.io/, which uses "yo".

# How to use:
## yeo surname subname setting1 setting2 setting3 setting4 -o option1 option2 option3 

# Put the path to the setting file here
YEOSET=/var/local/yeo/yeo.set

# Include the setting file
. ${YEOSET}


# Settings, Options, and input variables

## Parse arguments
SURNAME=${1}
SUBNAME=${2}
RUNSERF=${SURNAME}${SUBNAME}
ALLARGS=($@)
SERFSET=$(echo ${ALLARGS} | sed "s/ -.*//") #Get the required settings
SERFOPT=$(echo ${ALLARGS} | sed "s/${SERFSET}//") #Get the options and their flags
ALLSETOPT=(${SERFSET} ${SERFOPT})
ALLSONAME=(${vsetnames[@]} ${voptnames[@]})
### Create an array of the input Settings for easy counting and matching
SERFSETARY=(${SERFSET})

## Get Serf meta
source ${SERFS}/${RUNSERF}

# Validity check functions

## Present (merely checks if a Setting is present in the command)
isPresent() {
local Present=$1
local vvar=$2
if [ -n $Present ]; then
isPresent=true; else
isPresent=false; fi

if [ $isPresent = false ]; then
echo "$vvar must be present."
exit 55; fi
}

## Choice (a set of multiple-choice options)
isChoice() {
local Choice=$1
local vvar=$2
local vchoices=$3
if [ echo $vchoices | grep $Choice ]; then
isChoice=true; else
isChoice=false; fi

if [ $isChoice = false ]; then
echo "$vvar must be one of: $vchoices."
exit 55; fi
}

## NA OR...
isNAopt() {
local NAopt=$1
local vvar=$2
if [ -n $NA ]; then
isNAopt=true; else
isNAopt=false; fi

if [ $isNAopt = false ]; then
echo "$vvar must be present."
exit 55; fi
}

## IP4
### Thanks http://www.linuxjournal.com/content/validating-ip-address-bash-script
isIP4() {
local IP4=$1
local vvar=$2
if [[ $IP4 =~ ^[:digit:]{1,3}\.[:digit:]{1,3}\.[:digit:]{1,3}\.[:digit:]{1,3}$ ]]; then
### Create 4 separate variables
OIFS=$IFS
IFS='.'
ip=($IP4)
IFS=$OIFS
 if [[ ${IP4[0]} -le 255 && ${IP4[1]} -le 255 && ${IP4[2]} -le 255 && ${IP4[3]} -le 255 ]]; then
 isIP4=true; else
 isIP4=false; fi
else
isIP4=false;
fi

if [ $isIP4 = false ]; then
echo "$vvar must be a valid IP4 address."
exit 55; fi
}

## IP6
### Thanks https://stackoverflow.com/questions/31457586/how-can-i-check-ip-version-4-or-6-in-shell-script #Native POSIX (no bashisms) solution without external calls
isIP6() {
local IP6=$1
local vvar=$2
if [ "$IP6" != "${IP6#[:xdigit:]*:}" ] && [ "$IP6" = "${IP6#*[^:xdigit:]}" ] && [ "${IP6#*[:xdigit:][:xdigit:][:xdigit:][:xdigit:][:xdigit:]}" = "${IP6#*:*:*:*:*:*:*:*:*:}" ]; then
isIP6=true; else
isIP6=false; fi

if [ $isIP6 = false ]; then
echo "$vvar must be a valid IP6 address."
exit 55; fi
}

## Integer
isInt() {
local Int=$1
local vvar=$2
if [[ "$Int" =~ [:digit:]+$ ]]; then
isInt=true; else
isInt=false; fi

if [ $isInt = false ]; then
echo "$vvar must be a valid integer."
exit 55; fi
}

## Float
isInt() {
local Int=$1
local vvar=$2
if [[ "$Int" =~ [-+]?[:digit:]+\.?[:digit:]*$ ]]; then
isInt=true; else
isInt=false; fi

if [ $isInt = false ]; then
echo "$vvar must be a valid integer or decimal."
exit 55; fi
}

## HEX
### Thanks https://stackoverflow.com/questions/7662465/bash-is-there-a-simple-way-to-check-whether-a-string-is-a-valid-sha-1-or-md5
isHEX() {
local HEX=$1
local vvar=$2
if [[ "$HEX" =~ [:xdigit:]+$ ]]; then
isHEX=true; else
isHEX=false; fi

if [ $isHEX = false ]; then
echo "$vvar must be hexadecimal."
exit 55; fi
}

## az
isaz() {
local az=$1
local vvar=$2
if [[ "$az" =~ [:lower:]+$ ]]; then
isaz=true; else
isaz=false; fi

if [ $isaz = false ]; then
echo "$vvar must only include lowercase letters."
exit 55; fi
}

## azAZ
isazAZ() {
local azAZ=$1
local vvar=$2
if [[ "$azAZ" =~ [:alpha:]+$ ]]; then
isazAZ=true; else
isazAZ=false; fi

if [ $isazAZ = false ]; then
echo "$vvar must only include uppercase and/or lowercase letters."
exit 55; fi
}

## az09
isaz09() {
local az09=$1
local vvar=$2
if [[ "$az09" =~ [[:lower:][:digit:]]+$ ]]; then
isaz09=true; else
isaz09=false; fi

if [ $isaz09 = false ]; then
echo "$vvar must only include lowercase letters and/or digits."
exit 55; fi
}

## AZ09
isAZ09() {
local AZ09=$1
local vvar=$2
if [[ "$AZ09" =~ [[:upper:][:digit:]]+$ ]]; then
isAZ09=true; else
isAZ09=false; fi

if [ $isAZ09 = false ]; then
echo "$vvar must only include lowercase letters and/or digits."
exit 55; fi
}

## azAZ09
isazAZ09() {
local azAZ09=$1
local vvar=$2
if [[ "$azAZ09" =~ [:alnum:]+$ ]]; then
isazAZ09=true; else
isazAZ09=false; fi

if [ $isazAZ09 = false ]; then
echo "$vvar must only include uppercase letters, lowercase letters, and/or digits."
exit 55; fi
}

## azAZ09Punct (alphanumeric & Punctuation Characters)
isazAZ09Punct() {
local azAZ09Punct=$1
local vvar=$2
if [[ "$azAZ09Punct" =~ [:graph:]+$ ]]; then
isazAZ09Punct=true; else
isazAZ09Punct=false; fi

if [ $isazAZ09Punct = false ]; then
echo "$vvar must only include uppercase letters, lowercase letters, digits, and/or punctuation."
exit 55; fi
}

## FileDir ([azAZ09.-_])
isFileDir() {
local FileDir=$1
local vvar=$2
if [[ "$FileDir" =~ [[:alnum:]\.\-_]+$ ]]; then
isFileDir=true; else
isFileDir=false; fi

if [ $isFileDir = false ]; then
echo "$vvar must be a \"normal\" filename: alphanumeric; CAPS, hyphen, and underscore allowed; but no other special characters or spaces."
exit 55; fi
}

## URL (http{s}://[az09.].az)
isURL() {
local Domain=$1
local vvar=$2
if [[ "$Domain" =~ "http"+[s]?"://"+[[:lower:][:digit:]\.\-_]+\.[:lower:]+$ ]]; then
isDomain=true; else
isDomain=false; fi

if [ $isDomain = false ]; then
echo "$vvar must be a \"normal\" URL: domain, including alphanumeric characters, underscore, and hyphen, subdomains allowed, preceeded by either http:// or https://"
exit 55; fi
}

## Domain (az09.az)
isDomain() {
local Domain=$1
local vvar=$2
if [[ "$Domain" =~ [[:lower:][:digit:]\.\-_]+\.[:lower:]+$ ]]; then
isDomain=true; else
isDomain=false; fi

if [ $isDomain = false ]; then
echo "$vvar must be a \"normal\" domain, including alphanumeric characters, underscore, and hyphen, subdomains allowed if included, ie:  inksaverb.com  sub.inkisaverb.com  etc.sub.inkisaverb.com"
exit 55; fi
}

## verbTLD (valid, accepted TLDs; not full, proper verbURI)
isverbTLD() {
local verbTLD=$1
local vvar=$2
if [ echo ${VERBTLDS[@]} | grep $verbTLD ]; then
isverbTLD=true; else
isverbTLD=false; fi

if [ $isverbTLD = false ]; then
echo "$vvar must a valid verb TLD."
exit 55; fi
}


# Serf Management

## Get all surnames
getSurnames() {
cat ${YEOPB}
}

## Get all subnames for the surname
getSubnames() {
SURNAME=$1
for SUBNAME in ${SERFS}/${SURNAME}*; do
listSubName=$(echo ${SUBNAME} | sed "s/${SURNAME}//")
echo ${listSubName}
done
}

### Get hierarchy (the top-down priority rank of Serfs running Serfs)
#getHierarchy() {
#
#}

## Usage message
usageMessage()
{
echo "
Help:  ${SURNAME} ${SUBNAME} --h or --help  (to see this information)

${usagenotes}

Usage: ${SURNAME} ${SUBNAME} ${vsetslugs[@]} [Optional settings, se below ]
Options:"
local k=0
while [ $k != ${#voptflags[@]} ]; do
echo " -${voptflags[$k]}  ${voptnames[$k]}"
k=`expr ${k} + 1`
done
### Display any multiple choice options
if [ echo ${vopttypes[$k]} | grep "Choice" ]; then
#### Create an Options array and assign the Flags as keys to the Option Type values of the array
##### Later we recall the value of $type_element as: ${!optsTypeFAK[$optFlagKey]}
 local k=0
 declare -A optsTypeFAK
 while [ $k != ${#voptflags[@]} ]; do
 optsTypeFAK[${voptflags[$k]}]=${vopttypes[$k]}
 k=`expr ${k} + 1`
 done
#### List each Choice description
 for flg in "${!optsTypeFAK[@]}"; do
   if [[ "${optsTypeFAK[$flg]}" = "Choice" ]]; then
    local flagChoices="voptFC_$flg"
    echo " -$flg  Choose: ${!flagChoices}"
   fi
 done
fi
}

## Validate the Settings of the Serf
getSetValidation() {

### Check that all settings are present
if [ ${#SERFSETARY[@]} = ${#vsetnames[@]} ]; then
setCount=true; else
setCount=false
echo "Include all settings:"
#### Put each element on its own line
printf '%s\n' "${vsetnames[@]}"
exit 55; fi

### Validate each setting and option
local k=0
for SETINPUT in ${SERFSETARY[@]}; do
#### Prepare any multiple choice Settings
##### Two-stage empty set to avoid errors when not a Choice Type
 local showOptChoices=NULLCHOICES
 local NULLCHOICES=
 if [ "${vsettypes[$k]}" = "Choice" ]; then
  showSetChoices="vsetMC_$k"
 fi
#### Run the check
is${vsettypes[$k]} $SETINPUT "${vsetnames[$k]}" "${!showSetChoices}"
k=`expr ${k} + 1`
done

### Declare results
${RUNSERF}SetVal=true
return 0
}

## Validate the Options of the Serf
getOptValidation() {

### Create an Options array and assign the Flags as keys to the Option Type values of the array
#### Later we recall the value of $type_element as: ${!optsTypeFAK[$optFlagKey]}
local k=0
declare -A optsTypeFAK
while [ $k != ${#voptflags[@]} ]; do
optsTypeFAK[${voptflags[$k]}]=${vopttypes[$k]}
k=`expr ${k} + 1`
done

### Create an Options array and assign the Flags as keys to the Option Slug values of the array
#### Later we recall the value of $slug_element as: ${!optsSlugFAK[$optFlagKey]}
local k=0
declare -A optsSlugFAK
while [ $k != ${#voptflags[@]} ]; do
optsSlugFAK[${voptflags[$k]}]=${voptslugs[$k]}
k=`expr ${k} + 1`
done

### Create an Options Name array and assign the Flags as keys to the Option Name values of the array
#### Later we recall the value of $name_element as: ${!optsSlugFAK[$optFlagKey]}
local k=0
declare -A optsNameFAK
while [ $k != ${#voptflags[@]} ]; do
optsNameFAK[${voptflags[$k]}]="${voptnames[$k]}"
k=`expr ${k} + 1`
done

### Declare the Option Input variables as NULLIN now so setting Options requires positive attendance
for optFlagKey in ${voptflags[@]}; do
#### We set the value of the Type as NULLIN, ie $Int=NULLIN, $Domain=NULLIN, thanks https://unix.stackexchange.com/questions/23111/what-is-the-eval-command-in-bash
local eval ${optsSlugFAK[$optFlagKey]}=NULLIN
done

### Create a getops list
local optGetopts=
for optF in ${voptflags[@]}; do
optGetopts="${optGetopts}${optF}:"
done

### Check the Flags with getopts
#### Begin the options with a colon for silent error reporting
while getopts :h${optGetopts} vOptInput; do
case $vOptInput in
#### Help option
# h)
#  usageMessage
#  exit 0
#  ;;
#### Each Flag and Opiton in turn
 for optFlagKey in ${voptflags[@]}; do
 ${optFlagKey})
##### Set the argument to match the value of $slug_element
  local eval ${optsSlugFAK[$optFlagKey]}=$OPTARG
##### Prepare any multiple choice Options
###### Two-stage empty set to avoid errors when not a Choice Type
  local showOptChoices=NULLCHOICES
  local NULLCHOICES=
  if [[ "${optsTypeFAK[$optFlagKey]}" = "Choice" ]]; then
   showOptChoices="voptFC_$optFlagKey"
  fi
##### Run the validation function on that Type or if empty say so
  is${optsTypeFAK[$optFlagKey]} ${!optsSlugFAK[$optFlagKey]} "${optsNameFAK[$optFlagKey]}" "${!showOptChoices}"
  ;;
 done
esac
done
####DEV: http://wiki.bash-hackers.org/howto/getopts_tutorial
####     https://rsalveti.wordpress.com/2007/04/03/bash-parsing-arguments-with-getopts/
####     https://jonalmeida.com/posts/2013/05/26/different-ways-to-implement-flags-in-bash/
####     https://stackoverflow.com/questions/7069682/how-to-get-arguments-with-flags-in-bash-script

### Put options in correct order
for optFlagKey in ${voptflags[@]}; do
ORDEREDOPT="${ORDEREDOPT} ${!optsFAK[$optFlagKey]}"
done

#done ##DEV: remove if it works, this may be an orphan

### Declare results
${RUNSERF}OptVal=true
return 0
}


# Help?
if [ "$3" == "--h" ] || [ "$3" == "--help" ]; then
usageMessage
exit 0; fi

# Run the Serf
getSetValidation
getOptValidation 
${SERFS}/${RUNSERF} ${SERFSET} ${ORDEREDOPT}








