#!/bin/bash
#inkVerbYeo! verb.ink

# This is the "Yeoman" who manages a Verber by interacting with "Serfs", "Knights", the "Donjon", et cetera.
## This uses "yeo" to execute commands relevant to a Verber, similarly to how "apt", "yum", and "pacman" manage packages.
## yeo streamlines help queries, checks for required parameters, and provides a production-worthy layer of "fool-proofing".
## yeo retrieves available options, tools, settings, notes, parameter requirements, et cetera from the Verber assets themselves using functions & tools like grep and occasionally a central index. This is partially why formatting Serfs is important.
## This is NOT at all affiliated with http://yeoman.io/, which uses "yo".

# How to use:
## yeo surname subname setting1 setting2 setting3 setting4 -o option1 option2 option3

# Put the path to the setting file here
#YEOSET=/opt/yeo/yeo.set
export YEOSET="/home/jc/Dropbox/DocTools/Dev/vrk-verb-ink/yeo/yeo.set"
## Include the settings & functions
source ${YEOSET}
source ${yDir}/yeo.functions

# Settings, Options, and input variables
## Parse arguments
export SURNAME=${1}
export SUBNAME=${2}
shift 2
export ALLARGS=($@)
echo "${ALLARGS}"
# Help?
## Yeo
if [ "${SURNAME}" == "-h" ] || [ "${SURNAME}" == "--help" ]; then
usageYeo
exit 0; fi

## Surname
if [ "${SUBNAME}" == "-h" ] || [ "${SUBNAME}" == "--help" ]; then
usageSur "${SURNAME}"
exit 0; fi

# Lists
## Yeo
if [ "${SURNAME}" == "-s" ] || [ "${SURNAME}" == "--sur" ]; then
getSurnames
exit 0; fi

## Surname
if [ "${SUBNAME}" == "-s" ] || [ "${SUBNAME}" == "--sub" ]; then
getSubnames "${SURNAME}"
exit 0; fi

# Run the Serf
${SERFS}/${SURNAME}${SUBNAME}.ys "${ALLARGS}"
