#!/bin/bash

testedvar="$1"
testdev2="$2"
yDir="/home/jc/Dropbox/DocTools/Dev/vrk-verb-ink/yeo"
YEOPB="${yDir}/phonebooks/surnames.pb"
vDir="/home/jc/Dropbox/DocTools/Dev/vrk-verb-ink/yeo"
SERFS="${vDir}/serfs"

testFunction() {
TEST FUNCTION HERE
}

testFunction "$testedvar" "$testdev2"
