#!/bin/bash

testedvar="$1"
testdev2="$2"
yDir="/home/jc/Dropbox/DocTools/Dev/vrk-verb-ink/yeo"
PHPCITIES="${yDir}/PHPcities"
testFunction() {
cat "${PHPCITIES}"
}

testFunction "$testedvar" "$testdev2"
